/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'navy': {
          '50': '#eff3ff',
          '100': '#dbe4fe',
          '200': '#bfcffe',
          '300': '#93aefd',
          '400': '#6088fa',
          DEFAULT: '#3b6bf6',
          '600': '#2558eb',
          '700': '#1d4dd8',
          '800': '#1e44af',
          '900': '#1e3a8a',
          '950': '#172754',
        },
        'background': '#ffffff',
        'foreground': '#172754',
        'card': '#ffffff',
        'card-foreground': '#172754',
        'popover': '#ffffff',
        'popover-foreground': '#172754',
        'primary': '#3b6bf6',
        'primary-foreground': '#d2d2d2',
        'secondary': '#dbe4fe',
        'secondary-foreground': '#1e3a8a',
        'muted': '#dbe4fe',
        'muted-foreground': '#5a5a5a',
        'accent': '#dbe4fe',
        'accent-foreground': '#1e3a8a',
        'destructive': '#f63b3b',
        'destructive-foreground': '#d2d2d2',
        'border': '#d2d2d2',
        'input': '#d2d2d2',
        'ring': '#172754',
        'radius': '0.5rem',
        'chart-1': '#e6a0a0',
        'chart-2': '#a3c77b',
        'chart-3': '#9cb27e',
        'chart-4': '#6f9eaf',
        'chart-5': '#4c9c6a',
      },
    },
  },
  plugins: [],
};
